name: Daily APOD Fetch

on:
  schedule:
      - cron: '0 16 * * *'  # 09:00 PT / 16:00 UTC
        workflow_dispatch:

        jobs:
          fetch-and-commit:
              runs-on: ubuntu-latest
                  steps:
                        - name: Checkout repo
                                uses: actions/checkout@v4

                                      - name: Set up Python
                                              uses: actions/setup-python@v4
                                                      with:
                                                                python-version: '3.x'

                                                                      - name: Install dependencies
                                                                              run: |
                                                                                        python -m pip install --upgrade pip
                                                                                                  pip install -r requirements.txt

                                                                                                        - name: Run fetch_apod script
                                                                                                                env:
                                                                                                                          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
                                                                                                                                  run: |
                                                                                                                                            python fetch_apod.py
                                                                                                                                            
                                                                                                                                                  - name: Commit and push changes
                                                                                                                                                          run: |
                                                                                                                                                                    git config --global user.name 'apod-bot'
                                                                                                                                                                              git config --global user.email 'actions@github.com'
                                                                                                                                                                                        git add apod_archive/*
                                                                                                                                                                                                  git commit -m "chore: add daily APOD $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
                                                                                                                                                                                                            git push
